### ISSUE TITLE
autocomplete for channel parameter of schedule command fails to load

### ISSUE THREAD

**Issue by valbuildr** [valbuildr/bbcfansbot#6]
![image](https://github.com/valbuildr/bbcfansbot/assets/150450259/431f0562-4f96-4ac5-b98c-a5fd8b64bcbc)

**Comment by slipinthedove** [comment]
this seems to be because of too many autocomplete parameters at the same list. typing a more narrowed result (such as "One") lists the query as it should.

![image](https://github.com/valbuildr/bbcfansbot/assets/147140405/91a84a32-9a32-4e94-ab0d-8a577bd99b68)

no idea what to do here, either.

**Comment by valbuildr** [comment]
i think maybe splitting channel and region might be a good fix

**Comment by slipinthedove** [comment]
that sounds like a good idea (would need to check which of these contain "two" affiliate stations, tho; as it's not all of them) - i'll get to prototyping that with a smallfix to `verify_date` rn
